public enum SoundList
{
    ballHitsBrick,
    ballHitsWall,
    ballHitsBat,
    brickDestroyed,
    levelComplete,
    ballLost,
    multiBall,
    PointsCollected,
    LifeLost,

    ExtraLife,
    PowerUpShield,
    PowerUpLaser,
    PowerUpCrazyBall,
    PowerUpFireball,
    PowerUpSmallBat,
    PowerUpSplitBat,
    PowerUpWideBat,
    PowerUpFreeze,
    TNTBrick,

    MultiHitAwesome,
    MultiHitMadness,
    MultiHitExcellent,
    MultiHitBrilliant,
    MultiHitInsane,
    MultiHitWild,
    MultiHitUnbelievable,
    MultiHit,

    RounderBumper,
    LaserBulletHitsBrick,
    LaserBulletFiring,
    LaserBulletHitsWall,
    BallHitsShield,
    WanderingObstacleDestroyed,
    WanderingObstacleHit,
    AllBONUSLettersCollected,
    BONUSLetterCollected
}