public enum SoundList
{
    ballHitsBrick,
    ballHitsWall,
    ballHitsBat,
    brickDestroyed,
    levelComplete,
    ballLost,
    multiBall,
    PointsCollected,
    LifeLost,

    ExtraLife,
    PowerupShield,
    PowerupLaser,
    PowerupCrazyBall,
    PowerupFireball,
    PowerupSmallBat,
    PowerupSplitBat,
    PowerUpWideBat,
    PowerupFreeze,
    TNTBrick,

    MultiHitAwesome,
    MultiHitMadness,
    MultiHitExcellent,
    MultiHitBrilliant,
    MultiHitInsane,
    MultiHitWild,
    MultiHitUnbelievable,
    MultiHit,

    RounderBumper,
    LaserBulletHitsBrick,
    LaserBulletFiring,
    LaserBulletHitsWall,
    BallHitsShield,
    WanderingObstacleDestroyed,
    WanderingObstacleHit,
    AllBONUSLettersCollected,
    BONUSLetterCollected
}