// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class DataConstants
{
        public const string achievement_beat_the_level_66_boss = "CgkI0P-w_8QBEAIQCA"; // <GPGSID>
        public const string achievement_boss_1 = "CgkI0P-w_8QBEAIQAQ"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkI0P-w_8QBEAIQDQ"; // <GPGSID>
        public const string achievement_beat_the_level_40_boss = "CgkI0P-w_8QBEAIQBQ"; // <GPGSID>
        public const string achievement_beat_the_level_30_boss = "CgkI0P-w_8QBEAIQBA"; // <GPGSID>
        public const string achievement_break_10000_bricks = "CgkI0P-w_8QBEAIQDA"; // <GPGSID>
        public const string achievement_break_100_bricks = "CgkI0P-w_8QBEAIQCg"; // <GPGSID>
        public const string achievement_donate_to_the_developer = "CgkI0P-w_8QBEAIQCQ"; // <GPGSID>
        public const string achievement_beat_the_level_60_boss = "CgkI0P-w_8QBEAIQBw"; // <GPGSID>
        public const string achievement_beat_the_level_50_boss = "CgkI0P-w_8QBEAIQBg"; // <GPGSID>
        public const string achievement_break_1000_bricks = "CgkI0P-w_8QBEAIQCw"; // <GPGSID>
        public const string achievement_beat_the_level_20_boss = "CgkI0P-w_8QBEAIQAw"; // <GPGSID>
        public const string achievement_beat_the_level_10_boss = "CgkI0P-w_8QBEAIQAg"; // <GPGSID>

}

